version: '3.8'

services:
  # Elasticsearch - Log Storage and Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: code-visualizer-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk-network

  # Logstash - Log Processing and Transformation
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: code-visualizer-logstash
    ports:
      - "5044:5044"
      - "5001:5001/tcp"
      - "5001:5001/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elk/logstash/config:/usr/share/logstash/pipeline
      - ./elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elk-network
    depends_on:
      - elasticsearch

  # Kibana - Log Visualization and Analysis
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: code-visualizer-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elk-network
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:

networks:
  elk-network:
    driver: bridge
